### PR TITLE
Do not rely on window in _unsafeReadProtoTagged

### LINKED ISSUE #10: _unsafeReadProtoTagged should not rely on window
Current implementation of `_unsafeReadProtoTagged` relies on the window object
```
if (typeof window !== "undefined") {
    var ty = window[name];
    if (ty != null && value instanceof ty) {
      return just(value);
    }
```
But it's possible that the value or event comes from a different window context, like an event from iframe, then `value instanceof ty` will fail.

### PR DESCRIPTION
**Pull request by rnons**
Close #10 

A reproducible (on Chrome) example is here https://codepen.io/rnons/pen/gObLQzY?editors=1011

```html
<!-- index.html -->
<iframe></iframe>
<script>
const iframe = document.querySelector('iframe')
  iframe.contentWindow.addEventListener('click', ev => {
    console.log(ev.constructor.name)
    console.log(ev instanceof window.MouseEvent) // false!
  })
</script>
```

### CODE REVIEW

**Review by thomashoneyman — APPROVED** [review]

**Comment by garyb** [comment]
Maybe we could keep the early exit in the case of a positive result, but remove the early exit in the negative - the `instanceof` check should generally be faster than having to traverse the prototype chain.

File: src/Web/Internal/FFI.js [hunk 1]
```diff
@@ -1,13 +1,6 @@
 "use strict";
 
 exports._unsafeReadProtoTagged = function (nothing, just, name, value) {
-  if (typeof window !== "undefined") {
-    var ty = window[name];
-    if (ty != null && value instanceof ty) {
-      return just(value);
-    }
-    return nothing;
```
Comment (thomashoneyman) [inline src/Web/Internal/FFI.js:9]: @garyb Do you mean simply removing this line, so that we return early in case of a positive result, but fall through otherwise?

Comment (garyb) [reply src/Web/Internal/FFI.js:9]: Yeah, exactly.
